package airplay

import (
	"fmt"
	"reflect"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/BurntSushi/toml"
	"github.com/idio-sync/MiSTer_GroovyRelay/internal/adapters"
)

// Config is the [adapters.airplay] section.
type Config struct {
	Enabled           bool   `toml:"enabled"`
	Name              string `toml:"name"`        // advertised AirPlay speaker name
	BinaryPath        string `toml:"binary_path"` // shairport-sync; empty = PATH lookup
	AudioOutput       string `toml:"audio_output"`
	PauseGraceSeconds int    `toml:"pause_grace_seconds"`
	Port              int    `toml:"port"` // RTSP; 5000 is the AirPlay 1 default
}

const (
	AudioOutputMonitor    = "monitor"
	AudioOutputVisualOnly = "visual_only"

	maxPauseGraceSeconds = 600
	maxNameLength        = 63 // mDNS instance names are capped at 63 bytes
)

func DefaultConfig() Config {
	return Config{
		Name:              "MiSTer CRT",
		AudioOutput:       AudioOutputMonitor,
		PauseGraceSeconds: 30,
		Port:              5000,
	}
}

func decodeConfig(raw toml.Primitive, meta toml.MetaData) (Config, error) {
	cfg := DefaultConfig()
	if reflect.ValueOf(raw).IsZero() {
		return cfg, nil
	}
	if err := meta.PrimitiveDecode(raw, &cfg); err != nil {
		return Config{}, err
	}
	return cfg, nil
}

func (c Config) Validate() error {
	var errs adapters.FieldErrors
	name := strings.TrimSpace(c.Name)
	switch {
	case name == "":
		errs = append(errs, adapters.FieldError{Key: "name", Msg: "must not be empty"})
	case len(name) > maxNameLength:
		errs = append(errs, adapters.FieldError{Key: "name", Msg: fmt.Sprintf("must be at most %d bytes", maxNameLength)})
	case !utf8.ValidString(name) || strings.IndexFunc(name, unicode.IsControl) >= 0:
		errs = append(errs, adapters.FieldError{Key: "name", Msg: "must be printable text"})
	}
	if strings.ContainsAny(c.BinaryPath, "\r\n") {
		errs = append(errs, adapters.FieldError{Key: "binary_path", Msg: "must be a single path"})
	}
	switch c.AudioOutput {
	case AudioOutputMonitor, AudioOutputVisualOnly:
	default:
		errs = append(errs, adapters.FieldError{Key: "audio_output", Msg: fmt.Sprintf("must be %q or %q", AudioOutputMonitor, AudioOutputVisualOnly)})
	}
	if c.PauseGraceSeconds < 0 || c.PauseGraceSeconds > maxPauseGraceSeconds {
		errs = append(errs, adapters.FieldError{Key: "pause_grace_seconds", Msg: fmt.Sprintf("must be 0 to %d", maxPauseGraceSeconds)})
	}
	if c.Port < 1 || c.Port > 65535 {
		errs = append(errs, adapters.FieldError{Key: "port", Msg: "must be 1 to 65535"})
	}
	return errs.Err()
}

// helperSettings are the fields baked into the shairport-sync config
// file; changing any of them restarts the helper.
func (c Config) helperSettings() [3]any {
	return [3]any{strings.TrimSpace(c.Name), strings.TrimSpace(c.BinaryPath), c.Port}
}

// renderShairportConf writes the shairport-sync configuration (libconfig
// syntax) for cfg, sending metadata to the bridge on 127.0.0.1:metaPort.
func renderShairportConf(cfg Config, metaPort int) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by mister-groovy-relay for the airplay adapter; rewritten on every start.\n")
	fmt.Fprintf(&b, "general =\n{\n")
	fmt.Fprintf(&b, "  name = %s;\n", libconfigString(strings.TrimSpace(cfg.Name)))
	fmt.Fprintf(&b, "  port = %d;\n", cfg.Port)
	fmt.Fprintf(&b, "  output_backend = \"stdout\";\n")
	// A second phone takes over instead of being refused, and a vanished
	// sender releases the receiver quickly.
	fmt.Fprintf(&b, "  allow_session_interruption = \"yes\";\n")
	fmt.Fprintf(&b, "  session_timeout = 20;\n")
	fmt.Fprintf(&b, "};\n\n")
	fmt.Fprintf(&b, "metadata =\n{\n")
	fmt.Fprintf(&b, "  enabled = \"yes\";\n")
	fmt.Fprintf(&b, "  include_cover_art = \"yes\";\n")
	fmt.Fprintf(&b, "  cover_art_cache_directory = \"\";\n") // no on-disk art cache
	fmt.Fprintf(&b, "  socket_address = \"127.0.0.1\";\n")
	fmt.Fprintf(&b, "  socket_port = %d;\n", metaPort)
	fmt.Fprintf(&b, "  socket_msglength = 65000;\n")
	fmt.Fprintf(&b, "};\n")
	return b.String()
}

// libconfigString quotes s as a libconfig string literal.
func libconfigString(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}
